In [1]:
from BasisFilter import BasisFilter
import pandas as pd
import os
import copy
import numpy as np
import re

In [2]:
BF = BasisFilter()

In [3]:
dataset = pd.read_csv(f'{BF.path}//filtered_data//체중감량 예측모델 데이터셋.csv')

In [4]:
X = dataset.iloc[:,:33]
Y = dataset.iloc[:,33:]

In [5]:
X = X.drop('Date_1', axis =1)

In [6]:
# 각 열의 중간값 계산
medians = X.median()
# 결측값을 각 열의 중간값으로 채우기
X = X.fillna(medians)

In [7]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1805 entries, 0 to 1804
Data columns (total 32 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Age                          1805 non-null   float64
 1   PatientSex                   1805 non-null   int64
 2   Height                       1805 non-null   float64
 3   Coffee_기타                    1805 non-null   int64
 4   Coffee_마시지않음                 1805 non-null   int64
 5   Coffee_없음                    1805 non-null   int64
 6   Coffee_있음                    1805 non-null   int64
 7   Alcohol_거의 마시지 않는다 (월 1-2회)  1805 non-null   int64
 8   Alcohol_기타                   1805 non-null   int64
 9   Alcohol_주 1회                 1805 non-null   int64
 10  Alcohol_주 2회 이상              1805 non-null   int64
 11  HanbangX                     1805 non-null   int64
 12  HanbangYX                    1805 non-null   int64
 13  HanbangYY                    1805 non-null   int64
 14  YangbangX                    1805 non-null   int64
 15  YangbangYX                   1805 non-null   int64
 16  YangbangYY                   1805 non-null   int64
 17  BMI_1                        1805 non-null   float64
 18  BMR_1                        1805 non-null   float64
 19  FatFreeMass_1                1805 non-null   float64
 20  MaxVital_1                   1805 non-null   float64
 21  MinVital_1                   1805 non-null   float64
 22  PBF_1                        1805 non-null   float64
 23  Pulse_1                      1805 non-null   float64
 24  SMM_1                        1805 non-null   float64
 25  SoftLeanMass_1               1805 non-null   float64
 26  VFA_1                        1805 non-null   float64
 27  WHR_1                        1805 non-null   float64
 28  Weight_1                     1805 non-null   float64
 29  apedrin1                     1805 non-null   int64
 30  apedrin2                     1805 non-null   int64
 31  Period                       1805 non-null   float64
dtypes: float64(15), int64(17)
memory usage: 451.4 KB

In [8]:
Y.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1805 entries, 0 to 1804
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Weight_After         1805 non-null   float64
 1   BMI_After            1805 non-null   float64
 2   SMM_After            1805 non-null   float64
 3   PBF_After            1805 non-null   float64
 4   SoftLeanMass_After   1805 non-null   float64
 5   FatFreeMass_After    1805 non-null   float64
 6   VFA_After            1805 non-null   float64
 7   WHR_After            1805 non-null   float64
 8   BMR_After            1805 non-null   float64
 9   MaxVital_After       1770 non-null   float64
 10  MinVital_After       1770 non-null   float64
 11  Pulse_After          1770 non-null   float64
 12  PercentOfLossWeight  1805 non-null   float64
dtypes: float64(13)
memory usage: 183.4 KB

In [9]:
#Y에 vital이 없는 경우는 X에서 데이터를 따로 뽑아 진행해야할 듯함

In [10]:
X.describe()

,Age,PatientSex,Height,Coffee_기타,Coffee_마시지않음,Coffee_없음,Coffee_있음,Alcohol_거의 마시지 않는다 (월 1-2회),Alcohol_기타,Alcohol_주 1회,...,PBF_1,Pulse_1,SMM_1,SoftLeanMass_1,VFA_1,WHR_1,Weight_1,apedrin1,apedrin2,Period
count,1805.000000,1805.000000,1805.000000,1805.000000,1805.000000,1805.000000,1805.000000,1805.000000,1805.000000,1805.000000,...,1805.000000,1805.000000,1805.000000,1805.000000,1805.000000,1805.000000,1805.000000,1805.000000,1805.000000,1805.000000
mean,39.828255,1.860942,162.722543,0.004432,0.042105,0.721330,0.232133,0.563435,0.006648,0.218283,...,38.920886,84.750139,25.290028,43.440222,145.046205,0.930094,75.812964,109.044321,115.756233,89.727978
std,11.689079,0.346103,8.067549,0.066445,0.200885,0.448469,0.422310,0.496097,0.081288,0.413195,...,5.760083,12.990452,5.318260,8.299702,39.226295,0.061214,13.752251,11.250190,11.795390,15.489705
min,19.000000,1.000000,55.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,18.300000,0.000000,16.000000,29.000000,51.700000,0.700000,49.900000,80.000000,80.000000,23.000000
25%,30.000000,2.000000,158.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,35.600000,76.000000,21.800000,38.000000,115.800000,0.890000,65.900000,105.000000,105.000000,79.000000
50%,39.000000,2.000000,162.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000,...,39.000000,83.000000,23.900000,41.400000,141.000000,0.920000,72.600000,105.000000,115.000000,91.000000
75%,49.000000,2.000000,167.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000,...,42.600000,93.000000,26.700000,45.700000,170.000000,0.970000,82.700000,115.000000,125.000000,100.000000
max,71.000000,2.000000,190.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,55.900000,133.000000,55.800000,90.900000,280.700000,1.220000,149.300000,145.000000,145.000000,120.000000

In [15]:
dataset.loc[dataset['Pulse_1'] == 0, 'Pulse_1'] = 83
dataset.loc[dataset['MaxVital_1'] > 1000, 'MaxVital_1'] = medians['MaxVital_1']
dataset.loc[dataset['MinVital_1'] < 20, 'MinVital_1'] = medians['MinVital_1']
dataset.loc[dataset['WHR_1'] > 3, 'WHR_1'] = medians['WHR_1']
dataset['MaxVital_1'].fillna(medians['MaxVital_1'], inplace =True)
dataset['MinVital_1'].fillna(medians['MinVital_1'], inplace =True)
dataset['Pulse_1'].fillna(83, inplace =True)

In [16]:
dataset = dataset[dataset['BMI_1']<50]

In [17]:
dataset = dataset.drop('Date_1', axis = 1)

KeyError: "['Date_1'] not found in axis"

In [ ]:
import pandas as pd


# NaN이 포함된 열 찾기
nan_columns = dataset.columns[dataset.isna().any()].tolist()

print("Columns with NaN values:")
print(nan_columns)

In [18]:
import pandas as pd
import numpy as np
import itertools
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
from statsmodels.tools.eval_measures import aic, bic
import statsmodels.api as sm

X = dataset.iloc[:, :32]  # 특성
y = dataset.iloc[:, 32]  # 레이블

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [19]:
def calculate_metrics(X_train, y_train, X_test, y_test, selected_features):
    X_train_subset = X_train[selected_features]
    X_test_subset = X_test[selected_features]
    
    model = sm.OLS(y_train, sm.add_constant(X_train_subset)).fit()
    y_pred = model.predict(sm.add_constant(X_test_subset))
    
    # Adjusted R^2 계산
    adj_r2 = 1 - (1 - model.rsquared) * (len(y_test) - 1) / (len(y_test) - X_test_subset.shape[1] - 1)
    
    # AIC 및 BIC 계산
    aic_value = model.aic
    bic_value = model.bic
    
    return adj_r2, aic_value, bic_value

def get_feature_combinations(X_train):
    feature_combinations = []
    num_features = X_train.shape[1]
    
    for r in range(1, num_features + 1):
        combinations = itertools.combinations(X_train.columns, r)
        feature_combinations.extend(combinations)
    
    return feature_combinations

In [21]:
# 변수 조합 생성
feature_combinations = get_feature_combinations(X_train)

# 결과 저장을 위한 리스트
results = []

# 각 조합에 대해 메트릭 계산
for features in feature_combinations:
    adj_r2, aic_value, bic_value = calculate_metrics(X_train, y_train, X_test, y_test, features)
    results.append({
        'Features': features,
        'Adjusted R^2': adj_r2,
        'AIC': aic_value,
        'BIC': bic_value
    })
    print(f'Features: {features}, Adjusted R^2: {adj_r2}, AIC: {aic_value}, BIC: {bic_value}')

# DataFrame으로 변환
results_df = pd.DataFrame(results)

# 최적의 조합 찾기
best_adj_r2 = results_df.loc[results_df['Adjusted R^2'].idxmax()]
best_aic = results_df.loc[results_df['AIC'].idxmin()]
best_bic = results_df.loc[results_df['BIC'].idxmin()]

print("Best Adjusted R^2 Combination:", best_adj_r2)
print("Best AIC Combination:", best_aic)
print("Best BIC Combination:", best_bic)

# 시각화
plt.figure(figsize=(18, 6))

# Adjusted R^2
plt.subplot(1, 3, 1)
sns.scatterplot(x=results_df['Features'].apply(lambda x: len(x)), y=results_df['Adjusted R^2'])
plt.title('Adjusted R^2 vs Number of Features')
plt.xlabel('Number of Features')
plt.ylabel('Adjusted R^2')

# AIC
plt.subplot(1, 3, 2)
sns.scatterplot(x=results_df['Features'].apply(lambda x: len(x)), y=results_df['AIC'])
plt.title('AIC vs Number of Features')
plt.xlabel('Number of Features')
plt.ylabel('AIC')

# BIC
plt.subplot(1, 3, 3)
sns.scatterplot(x=results_df['Features'].apply(lambda x: len(x)), y=results_df['BIC'])
plt.title('BIC vs Number of Features')
plt.xlabel('Number of Features')
plt.ylabel('BIC')

plt.tight_layout()
plt.show()

MemoryError: